name: cross-job-workflow

on:
  # Trigger the action manually from the UI
  workflow_dispatch:

jobs:
  job1:
    name: List Dockerfiles
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dockerfile-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: List Dockerfiles
        id: dockerfile-matrix
        run: |
          echo "matrix=$(ls Dockerfile.* | sed 's/Dockerfile.//' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
          echo "somevar=yes" >> "$GITHUB_OUTPUT"

  build-and-push:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: debug matrix
        run: |
          echo "Matrix from job1: ${{ needs.job1.outputs.matrix }}"
          echo "Somevar from job1: ${{ needs.job1.outputs.somevar }}"
